ci: aptly

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -248,13 +248,22 @@ jobs:
         run: |
           SNAPSHOT_NAME="snapshot-$(date +%Y%m%d%H%M%S)"
           aptly snapshot create $SNAPSHOT_NAME from repo ${{ env.REPO_NAME }}
-          PUBLISH_RESULT=$(aptly publish snapshot -distribution=${{ env.DISTRIBUTION }} -gpg-key="${{ secrets.GPG_KEY_ID}}" $SNAPSHOT_NAME s3:dlaas/releases/${{ env.REPO_NAME }} 2>&1 || echo "PUBLISH_FAILED")
-          if [[ "$PUBLISH_RESULT" == *"PUBLISH_FAILED"* ]]; then
-            echo "Publication exists, updating..."
-            aptly publish update -gpg-key="${{ secrets.GPG_KEY_ID}}" ${{ env.DISTRIBUTION }} s3:dlaas/releases/${{ env.REPO_NAME }}
+      
+          # Attempt to publish the new snapshot. If it fails because the publication already exists, then update.
+          if ! aptly publish snapshot -distribution=${{ env.DISTRIBUTION }} -gpg-key="${{ secrets.GPG_KEY_ID }}" $SNAPSHOT_NAME s3:dlaas/releases/${{ env.REPO_NAME }}; then
+            echo "Publication exists, attempting to update..."
+            # Check if a publication for the distribution already exists before attempting to update
+            if aptly publish list | grep -q "${{ env.DISTRIBUTION }}"; then
+              echo "Updating existing publication..."
+              aptly publish switch -distribution=${{ env.DISTRIBUTION }} -gpg-key="${{ secrets.GPG_KEY_ID }}" s3:dlaas/releases $SNAPSHOT_NAME
+            else
+              echo "No publication found for distribution ${{ env.DISTRIBUTION }}. Initial publish attempt may have failed."
+              exit 1
+            fi
           else
             echo "Published new snapshot."
           fi
+        shell: bash
   
       - name: Create GPG Public Key File
         run: |
